[2024-09-20T13:12:59.635+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-20T13:12:59.651+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.load_data manual__2024-09-20T13:12:32.852119+00:00 [queued]>
[2024-09-20T13:12:59.660+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.load_data manual__2024-09-20T13:12:32.852119+00:00 [queued]>
[2024-09-20T13:12:59.660+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-20T13:12:59.848+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_data> on 2024-09-20 13:12:32.852119+00:00
[2024-09-20T13:12:59.857+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=164) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-20T13:12:59.858+0000] {standard_task_runner.py:72} INFO - Started process 166 to run task
[2024-09-20T13:12:59.859+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'load_data', 'manual__2024-09-20T13:12:32.852119+00:00', '--job-id', '261', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmp4jeq4qqm']
[2024-09-20T13:12:59.861+0000] {standard_task_runner.py:105} INFO - Job 261: Subtask load_data
[2024-09-20T13:12:59.898+0000] {task_command.py:467} INFO - Running <TaskInstance: NYC_Taxi_pipeline.load_data manual__2024-09-20T13:12:32.852119+00:00 [running]> on host 299ec99d9d69
[2024-09-20T13:12:59.975+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-20T13:12:32.852119+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-20T13:12:32.852119+00:00'
[2024-09-20T13:12:59.976+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-20T13:12:59.990+0000] {NYC_Taxi_pipeline.py:43} INFO - Start to load data
[2024-09-20T13:12:59.991+0000] {data_process.py:28} INFO - Loading data into table trip...
[2024-09-20T13:13:02.100+0000] {data_process.py:51} INFO - Data shape after dropna: (339807, 20)
[2024-09-20T13:13:02.103+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-09-20T13:13:17.053+0000] {data_process.py:77} ERROR - Error during data load: can't adapt type 'NAType'
[2024-09-20T13:13:17.149+0000] {NYC_Taxi_pipeline.py:46} INFO - Load data done
[2024-09-20T13:13:17.150+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-20T13:13:17.160+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-20T13:13:17.161+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=NYC_Taxi_pipeline, task_id=load_data, run_id=manual__2024-09-20T13:12:32.852119+00:00, execution_date=20240920T131232, start_date=20240920T131259, end_date=20240920T131317
[2024-09-20T13:13:17.201+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-20T13:13:17.214+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-20T13:13:17.215+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
