[2024-09-17T18:44:44.063+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-17T18:44:44.246+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.load_data manual__2024-09-17T18:44:41.133855+00:00 [queued]>
[2024-09-17T18:44:44.254+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.load_data manual__2024-09-17T18:44:41.133855+00:00 [queued]>
[2024-09-17T18:44:44.254+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-17T18:44:44.265+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_data> on 2024-09-17 18:44:41.133855+00:00
[2024-09-17T18:44:44.273+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=68) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-17T18:44:44.274+0000] {standard_task_runner.py:72} INFO - Started process 70 to run task
[2024-09-17T18:44:44.275+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'load_data', 'manual__2024-09-17T18:44:41.133855+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmp281xol88']
[2024-09-17T18:44:44.277+0000] {standard_task_runner.py:105} INFO - Job 197: Subtask load_data
[2024-09-17T18:44:44.315+0000] {task_command.py:467} INFO - Running <TaskInstance: NYC_Taxi_pipeline.load_data manual__2024-09-17T18:44:41.133855+00:00 [running]> on host 103d737d0864
[2024-09-17T18:44:44.391+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-17T18:44:41.133855+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-17T18:44:41.133855+00:00'
[2024-09-17T18:44:44.392+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-17T18:44:44.404+0000] {NYC_Taxi_pipeline.py:48} INFO - Start to load data
[2024-09-17T18:44:44.404+0000] {data_process.py:45} INFO - Loading data into table trip...
[2024-09-17T18:44:44.407+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-09-17T18:44:44.408+0000] {NYC_Taxi_pipeline.py:53} ERROR - Error in load
Traceback (most recent call last):
  File "/opt/airflow/dags/NYC_Taxi_pipeline.py", line 50, in load_data
    load_to_postres('trip', df, **db_credentials)
  File "/opt/airflow/dags/scripts/data_process.py", line 53, in load_to_postres
    for i, row in data_frame.iterrows():
                  ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'iterrows'
[2024-09-17T18:44:44.409+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-17T18:44:44.418+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-17T18:44:44.419+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=NYC_Taxi_pipeline, task_id=load_data, run_id=manual__2024-09-17T18:44:41.133855+00:00, execution_date=20240917T184441, start_date=20240917T184444, end_date=20240917T184444
[2024-09-17T18:44:44.448+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-17T18:44:44.466+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-17T18:44:44.467+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
