[2024-09-21T06:21:06.426+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-21T06:21:06.446+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.load_data scheduled__2024-09-20T00:00:00+00:00 [queued]>
[2024-09-21T06:21:06.453+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.load_data scheduled__2024-09-20T00:00:00+00:00 [queued]>
[2024-09-21T06:21:06.453+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-21T06:21:06.497+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2024-09-20 00:00:00+00:00
[2024-09-21T06:21:06.505+0000] {standard_task_runner.py:63} INFO - Started process 53 to run task
[2024-09-21T06:21:06.507+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'load_data', 'scheduled__2024-09-20T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmpsp7lm5ef']
[2024-09-21T06:21:06.510+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask load_data
[2024-09-21T06:21:06.589+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.load_data scheduled__2024-09-20T00:00:00+00:00 [running]> on host a7d215ebb90a
[2024-09-21T06:21:06.735+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-20T00:00:00+00:00'
[2024-09-21T06:21:06.736+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-21T06:21:06.750+0000] {NYC_Taxi_pipeline.py:44} INFO - Start to load data
[2024-09-21T06:21:06.751+0000] {data_process.py:28} INFO - Loading data into table trip...
[2024-09-21T06:21:08.776+0000] {data_process.py:51} INFO - Data shape after dropna: (339807, 20)
[2024-09-21T06:21:08.963+0000] {db_utils.py:24} ERROR - Error while connecting to PostgreSQL: connection to server at "172.20.0.3", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-09-21T06:21:08.964+0000] {data_process.py:74} ERROR - Failed to connect to the database and load data into table trip
[2024-09-21T06:21:08.986+0000] {NYC_Taxi_pipeline.py:47} INFO - Load data done
[2024-09-21T06:21:08.987+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-21T06:21:08.988+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-21T06:21:09.000+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=NYC_Taxi_pipeline, task_id=load_data, run_id=scheduled__2024-09-20T00:00:00+00:00, execution_date=20240920T000000, start_date=20240921T062106, end_date=20240921T062108
[2024-09-21T06:21:09.088+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-21T06:21:09.114+0000] {taskinstance.py:3498} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-09-21T06:21:09.148+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
