[2024-10-12T08:52:14.469+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-12T08:52:14.492+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_transformation_layer.dbt_run_model_green_trip scheduled__2024-10-12T08:00:00+00:00 [queued]>
[2024-10-12T08:52:14.505+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_transformation_layer.dbt_run_model_green_trip scheduled__2024-10-12T08:00:00+00:00 [queued]>
[2024-10-12T08:52:14.505+0000] {taskinstance.py:2306} INFO - Starting attempt 11 of 11
[2024-10-12T08:52:14.528+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_transformation_layer.dbt_run_model_green_trip> on 2024-10-12 08:00:00+00:00
[2024-10-12T08:52:14.538+0000] {standard_task_runner.py:63} INFO - Started process 59 to run task
[2024-10-12T08:52:14.542+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Taxi_trip_pipeline', 'dbt_transformation_layer.dbt_run_model_green_trip', 'scheduled__2024-10-12T08:00:00+00:00', '--job-id', '522', '--raw', '--subdir', 'DAGS_FOLDER/taxi_trip.py', '--cfg-path', '/tmp/tmpb1b2wmhd']
[2024-10-12T08:52:14.545+0000] {standard_task_runner.py:91} INFO - Job 522: Subtask dbt_transformation_layer.dbt_run_model_green_trip
[2024-10-12T08:52:14.624+0000] {task_command.py:426} INFO - Running <TaskInstance: Taxi_trip_pipeline.dbt_transformation_layer.dbt_run_model_green_trip scheduled__2024-10-12T08:00:00+00:00 [running]> on host f02ce4f01a3b
[2024-10-12T08:52:14.734+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='Taxi_trip_pipeline' AIRFLOW_CTX_TASK_ID='dbt_transformation_layer.dbt_run_model_green_trip' AIRFLOW_CTX_EXECUTION_DATE='2024-10-12T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-12T08:00:00+00:00'
[2024-10-12T08:52:14.735+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-12T08:52:14.747+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-12T08:52:14.748+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --profiles-dir /opt/***/DBT_Project  --project-dir /opt/***/dbt_trip --models green_trip']
[2024-10-12T08:52:14.762+0000] {subprocess.py:86} INFO - Output:
[2024-10-12T08:52:17.973+0000] {subprocess.py:93} INFO - [0m08:52:17  Running with dbt=1.8.0
[2024-10-12T08:52:18.311+0000] {subprocess.py:93} INFO - [0m08:52:18  Registered adapter: postgres=1.8.0
[2024-10-12T08:52:18.831+0000] {subprocess.py:93} INFO - [0m08:52:18  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-12T08:52:18.832+0000] {subprocess.py:93} INFO - There are 2 unused configuration paths:
[2024-10-12T08:52:18.832+0000] {subprocess.py:93} INFO - - models.fact_trip.Dimensions
[2024-10-12T08:52:18.832+0000] {subprocess.py:93} INFO - - models.fact_trip.staging
[2024-10-12T08:52:19.106+0000] {subprocess.py:93} INFO - [0m08:52:19  Found 4 models, 6 data tests, 3 sources, 566 macros
[2024-10-12T08:52:19.109+0000] {subprocess.py:93} INFO - [0m08:52:19
[2024-10-12T08:52:19.178+0000] {subprocess.py:93} INFO - [0m08:52:19
[2024-10-12T08:52:19.178+0000] {subprocess.py:93} INFO - [0m08:52:19  Finished running  in 0 hours 0 minutes and 0.07 seconds (0.07s).
[2024-10-12T08:52:19.179+0000] {subprocess.py:93} INFO - [0m08:52:19  Encountered an error:
[2024-10-12T08:52:19.180+0000] {subprocess.py:93} INFO - Database Error
[2024-10-12T08:52:19.180+0000] {subprocess.py:93} INFO -   connection to server at "172.20.0.3", port 5432 failed: Connection refused
[2024-10-12T08:52:19.180+0000] {subprocess.py:93} INFO -   	Is the server running on that host and accepting TCP/IP connections?
[2024-10-12T08:52:19.180+0000] {subprocess.py:93} INFO - 
[2024-10-12T08:52:20.171+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-10-12T08:52:20.172+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-12T08:52:20.187+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-10-12T08:52:20.191+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Taxi_trip_pipeline, task_id=dbt_transformation_layer.dbt_run_model_green_trip, run_id=scheduled__2024-10-12T08:00:00+00:00, execution_date=20241012T080000, start_date=20241012T085214, end_date=20241012T085220
[2024-10-12T08:52:20.205+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 522 for task dbt_transformation_layer.dbt_run_model_green_trip (Bash command failed. The command returned a non-zero exit code 2.; 59)
[2024-10-12T08:52:20.246+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-12T08:52:20.266+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-12T08:52:20.267+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
