[2024-10-01T09:27:26.831+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-01T09:27:26.852+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_yellow_trip scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-01T09:27:26.862+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_yellow_trip scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-01T09:27:26.862+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 5
[2024-10-01T09:27:26.874+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_staging_layer.dbt_run_yellow_trip> on 2024-09-30 00:00:00+00:00
[2024-10-01T09:27:26.881+0000] {standard_task_runner.py:63} INFO - Started process 370 to run task
[2024-10-01T09:27:26.884+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Taxi_trip_pipeline', 'dbt_staging_layer.dbt_run_yellow_trip', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/taxi_trip.py', '--cfg-path', '/tmp/tmpbs4iarwm']
[2024-10-01T09:27:26.886+0000] {standard_task_runner.py:91} INFO - Job 154: Subtask dbt_staging_layer.dbt_run_yellow_trip
[2024-10-01T09:27:26.929+0000] {task_command.py:426} INFO - Running <TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_yellow_trip scheduled__2024-09-30T00:00:00+00:00 [running]> on host fcb0f9e87e2b
[2024-10-01T09:27:27.007+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='Taxi_trip_pipeline' AIRFLOW_CTX_TASK_ID='dbt_staging_layer.dbt_run_yellow_trip' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T00:00:00+00:00'
[2024-10-01T09:27:27.008+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-01T09:27:27.019+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-01T09:27:27.019+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --profiles-dir /opt/***/DBT_Project  --project-dir /opt/***/dbt_trip --models yellow_trip']
[2024-10-01T09:27:27.033+0000] {subprocess.py:86} INFO - Output:
[2024-10-01T09:27:29.666+0000] {subprocess.py:93} INFO - [0m09:27:29  Running with dbt=1.8.0
[2024-10-01T09:27:29.966+0000] {subprocess.py:93} INFO - [0m09:27:29  Registered adapter: postgres=1.8.0
[2024-10-01T09:27:30.639+0000] {subprocess.py:93} INFO - [0m09:27:30  [[33mWARNING[0m]: Deprecated functionality
[2024-10-01T09:27:30.640+0000] {subprocess.py:93} INFO - The `tests` config has been renamed to `data_tests`. Please see
[2024-10-01T09:27:30.640+0000] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
[2024-10-01T09:27:30.640+0000] {subprocess.py:93} INFO - information.
[2024-10-01T09:27:30.873+0000] {subprocess.py:93} INFO - [0m09:27:30  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-01T09:27:30.874+0000] {subprocess.py:93} INFO - There are 2 unused configuration paths:
[2024-10-01T09:27:30.874+0000] {subprocess.py:93} INFO - - models.fact_trip.Dimensions
[2024-10-01T09:27:30.874+0000] {subprocess.py:93} INFO - - models.fact_trip.staging
[2024-10-01T09:27:31.049+0000] {subprocess.py:93} INFO - [0m09:27:31  Found 4 models, 6 data tests, 3 sources, 566 macros
[2024-10-01T09:27:31.051+0000] {subprocess.py:93} INFO - [0m09:27:31
[2024-10-01T09:27:31.181+0000] {subprocess.py:93} INFO - [0m09:27:31  Concurrency: 3 threads (target='dev')
[2024-10-01T09:27:31.183+0000] {subprocess.py:93} INFO - [0m09:27:31
[2024-10-01T09:27:31.199+0000] {subprocess.py:93} INFO - [0m09:27:31  1 of 1 START sql view model analysis.yellow_trip ............................... [RUN]
[2024-10-01T09:27:31.305+0000] {subprocess.py:93} INFO - [0m09:27:31  1 of 1 ERROR creating sql view model analysis.yellow_trip ...................... [[31mERROR[0m in 0.10s]
[2024-10-01T09:27:31.323+0000] {subprocess.py:93} INFO - [0m09:27:31
[2024-10-01T09:27:31.324+0000] {subprocess.py:93} INFO - [0m09:27:31  Finished running 1 view model in 0 hours 0 minutes and 0.27 seconds (0.27s).
[2024-10-01T09:27:31.376+0000] {subprocess.py:93} INFO - [0m09:27:31
[2024-10-01T09:27:31.377+0000] {subprocess.py:93} INFO - [0m09:27:31  [31mCompleted with 1 error and 0 warnings:[0m
[2024-10-01T09:27:31.377+0000] {subprocess.py:93} INFO - [0m09:27:31
[2024-10-01T09:27:31.378+0000] {subprocess.py:93} INFO - [0m09:27:31    Database Error in model yellow_trip (models/Staging/yellow_trip.sql)
[2024-10-01T09:27:31.378+0000] {subprocess.py:93} INFO -   column "lpep_pickup_datetime" does not exist
[2024-10-01T09:27:31.378+0000] {subprocess.py:93} INFO -   LINE 24:     ROW_NUMBER() OVER (ORDER BY "VendorID", "lpep_pickup_dat...
[2024-10-01T09:27:31.379+0000] {subprocess.py:93} INFO -                                                        ^
[2024-10-01T09:27:31.379+0000] {subprocess.py:93} INFO -   HINT:  Perhaps you meant to reference the column "source.tpep_pickup_datetime".
[2024-10-01T09:27:31.379+0000] {subprocess.py:93} INFO -   compiled code at target/run/fact_trip/models/Staging/yellow_trip.sql
[2024-10-01T09:27:31.379+0000] {subprocess.py:93} INFO - [0m09:27:31
[2024-10-01T09:27:31.380+0000] {subprocess.py:93} INFO - [0m09:27:31  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-10-01T09:27:32.387+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-01T09:27:32.388+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-01T09:27:32.399+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-01T09:27:32.403+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Taxi_trip_pipeline, task_id=dbt_staging_layer.dbt_run_yellow_trip, run_id=scheduled__2024-09-30T00:00:00+00:00, execution_date=20240930T000000, start_date=20241001T092726, end_date=20241001T092732
[2024-10-01T09:27:32.415+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 154 for task dbt_staging_layer.dbt_run_yellow_trip (Bash command failed. The command returned a non-zero exit code 1.; 370)
[2024-10-01T09:27:32.425+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-01T09:27:32.448+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-01T09:27:32.453+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
