[2024-10-01T10:45:55.018+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-01T10:45:55.045+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_green_trip manual__2024-10-01T10:32:20.925791+00:00 [queued]>
[2024-10-01T10:45:55.057+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_green_trip manual__2024-10-01T10:32:20.925791+00:00 [queued]>
[2024-10-01T10:45:55.058+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-10-01T10:45:55.075+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_staging_layer.dbt_run_green_trip> on 2024-10-01 10:32:20.925791+00:00
[2024-10-01T10:45:55.083+0000] {standard_task_runner.py:63} INFO - Started process 710 to run task
[2024-10-01T10:45:55.086+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Taxi_trip_pipeline', 'dbt_staging_layer.dbt_run_green_trip', 'manual__2024-10-01T10:32:20.925791+00:00', '--job-id', '178', '--raw', '--subdir', 'DAGS_FOLDER/taxi_trip.py', '--cfg-path', '/tmp/tmpno09brpk']
[2024-10-01T10:45:55.088+0000] {standard_task_runner.py:91} INFO - Job 178: Subtask dbt_staging_layer.dbt_run_green_trip
[2024-10-01T10:45:55.143+0000] {task_command.py:426} INFO - Running <TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_green_trip manual__2024-10-01T10:32:20.925791+00:00 [running]> on host fcb0f9e87e2b
[2024-10-01T10:45:55.247+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='Taxi_trip_pipeline' AIRFLOW_CTX_TASK_ID='dbt_staging_layer.dbt_run_green_trip' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T10:32:20.925791+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-01T10:32:20.925791+00:00'
[2024-10-01T10:45:55.249+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-01T10:45:55.266+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-01T10:45:55.267+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --profiles-dir /opt/***/DBT_Project  --project-dir /opt/***/dbt_trip --models green_trip']
[2024-10-01T10:45:55.281+0000] {subprocess.py:86} INFO - Output:
[2024-10-01T10:45:58.200+0000] {subprocess.py:93} INFO - [0m10:45:58  Running with dbt=1.8.0
[2024-10-01T10:45:58.532+0000] {subprocess.py:93} INFO - [0m10:45:58  Registered adapter: postgres=1.8.0
[2024-10-01T10:45:59.463+0000] {subprocess.py:93} INFO - [0m10:45:59  [[33mWARNING[0m]: Deprecated functionality
[2024-10-01T10:45:59.463+0000] {subprocess.py:93} INFO - The `tests` config has been renamed to `data_tests`. Please see
[2024-10-01T10:45:59.463+0000] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
[2024-10-01T10:45:59.464+0000] {subprocess.py:93} INFO - information.
[2024-10-01T10:45:59.740+0000] {subprocess.py:93} INFO - [0m10:45:59  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-01T10:45:59.741+0000] {subprocess.py:93} INFO - There are 2 unused configuration paths:
[2024-10-01T10:45:59.741+0000] {subprocess.py:93} INFO - - models.fact_trip.staging
[2024-10-01T10:45:59.741+0000] {subprocess.py:93} INFO - - models.fact_trip.Dimensions
[2024-10-01T10:46:00.006+0000] {subprocess.py:93} INFO - [0m10:46:00  Found 4 models, 6 data tests, 3 sources, 566 macros
[2024-10-01T10:46:00.008+0000] {subprocess.py:93} INFO - [0m10:46:00
[2024-10-01T10:46:00.156+0000] {subprocess.py:93} INFO - [0m10:46:00  Concurrency: 3 threads (target='dev')
[2024-10-01T10:46:00.157+0000] {subprocess.py:93} INFO - [0m10:46:00
[2024-10-01T10:46:00.171+0000] {subprocess.py:93} INFO - [0m10:46:00  1 of 1 START sql view model analysis.green_trip ................................ [RUN]
[2024-10-01T10:46:00.282+0000] {subprocess.py:93} INFO - [0m10:46:00  1 of 1 ERROR creating sql view model analysis.green_trip ....................... [[31mERROR[0m in 0.11s]
[2024-10-01T10:46:00.295+0000] {subprocess.py:93} INFO - [0m10:46:00
[2024-10-01T10:46:00.296+0000] {subprocess.py:93} INFO - [0m10:46:00  Finished running 1 view model in 0 hours 0 minutes and 0.29 seconds (0.29s).
[2024-10-01T10:46:00.350+0000] {subprocess.py:93} INFO - [0m10:46:00
[2024-10-01T10:46:00.350+0000] {subprocess.py:93} INFO - [0m10:46:00  [31mCompleted with 1 error and 0 warnings:[0m
[2024-10-01T10:46:00.351+0000] {subprocess.py:93} INFO - [0m10:46:00
[2024-10-01T10:46:00.352+0000] {subprocess.py:93} INFO - [0m10:46:00    Database Error in model green_trip (models/Staging/green_trip.sql)
[2024-10-01T10:46:00.352+0000] {subprocess.py:93} INFO -   syntax error at or near ""trip_type""
[2024-10-01T10:46:00.352+0000] {subprocess.py:93} INFO -   LINE 107:         "trip_type" AS trip_type,
[2024-10-01T10:46:00.352+0000] {subprocess.py:93} INFO -                     ^
[2024-10-01T10:46:00.352+0000] {subprocess.py:93} INFO -   compiled code at target/run/fact_trip/models/Staging/green_trip.sql
[2024-10-01T10:46:00.353+0000] {subprocess.py:93} INFO - [0m10:46:00
[2024-10-01T10:46:00.353+0000] {subprocess.py:93} INFO - [0m10:46:00  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-10-01T10:46:01.422+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-01T10:46:01.423+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-01T10:46:01.436+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-01T10:46:01.441+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Taxi_trip_pipeline, task_id=dbt_staging_layer.dbt_run_green_trip, run_id=manual__2024-10-01T10:32:20.925791+00:00, execution_date=20241001T103220, start_date=20241001T104555, end_date=20241001T104601
[2024-10-01T10:46:01.458+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 178 for task dbt_staging_layer.dbt_run_green_trip (Bash command failed. The command returned a non-zero exit code 1.; 710)
[2024-10-01T10:46:01.475+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-01T10:46:01.498+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-01T10:46:01.501+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
