[2024-10-01T10:46:27.068+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-01T10:46:27.089+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_green_trip manual__2024-10-01T10:32:20.925791+00:00 [queued]>
[2024-10-01T10:46:27.097+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_green_trip manual__2024-10-01T10:32:20.925791+00:00 [queued]>
[2024-10-01T10:46:27.097+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2024-10-01T10:46:27.108+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_staging_layer.dbt_run_green_trip> on 2024-10-01 10:32:20.925791+00:00
[2024-10-01T10:46:27.115+0000] {standard_task_runner.py:63} INFO - Started process 771 to run task
[2024-10-01T10:46:27.118+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Taxi_trip_pipeline', 'dbt_staging_layer.dbt_run_green_trip', 'manual__2024-10-01T10:32:20.925791+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/taxi_trip.py', '--cfg-path', '/tmp/tmpkpy6_csi']
[2024-10-01T10:46:27.120+0000] {standard_task_runner.py:91} INFO - Job 180: Subtask dbt_staging_layer.dbt_run_green_trip
[2024-10-01T10:46:27.161+0000] {task_command.py:426} INFO - Running <TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_green_trip manual__2024-10-01T10:32:20.925791+00:00 [running]> on host fcb0f9e87e2b
[2024-10-01T10:46:27.238+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='Taxi_trip_pipeline' AIRFLOW_CTX_TASK_ID='dbt_staging_layer.dbt_run_green_trip' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T10:32:20.925791+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-01T10:32:20.925791+00:00'
[2024-10-01T10:46:27.239+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-01T10:46:27.249+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-01T10:46:27.250+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --profiles-dir /opt/***/DBT_Project  --project-dir /opt/***/dbt_trip --models green_trip']
[2024-10-01T10:46:27.263+0000] {subprocess.py:86} INFO - Output:
[2024-10-01T10:46:29.875+0000] {subprocess.py:93} INFO - [0m10:46:29  Running with dbt=1.8.0
[2024-10-01T10:46:30.227+0000] {subprocess.py:93} INFO - [0m10:46:30  Registered adapter: postgres=1.8.0
[2024-10-01T10:46:30.862+0000] {subprocess.py:93} INFO - [0m10:46:30  [[33mWARNING[0m]: Deprecated functionality
[2024-10-01T10:46:30.862+0000] {subprocess.py:93} INFO - The `tests` config has been renamed to `data_tests`. Please see
[2024-10-01T10:46:30.862+0000] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
[2024-10-01T10:46:30.863+0000] {subprocess.py:93} INFO - information.
[2024-10-01T10:46:31.101+0000] {subprocess.py:93} INFO - [0m10:46:31  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-01T10:46:31.101+0000] {subprocess.py:93} INFO - There are 2 unused configuration paths:
[2024-10-01T10:46:31.101+0000] {subprocess.py:93} INFO - - models.fact_trip.Dimensions
[2024-10-01T10:46:31.102+0000] {subprocess.py:93} INFO - - models.fact_trip.staging
[2024-10-01T10:46:31.296+0000] {subprocess.py:93} INFO - [0m10:46:31  Found 4 models, 6 data tests, 3 sources, 566 macros
[2024-10-01T10:46:31.298+0000] {subprocess.py:93} INFO - [0m10:46:31
[2024-10-01T10:46:31.438+0000] {subprocess.py:93} INFO - [0m10:46:31  Concurrency: 3 threads (target='dev')
[2024-10-01T10:46:31.439+0000] {subprocess.py:93} INFO - [0m10:46:31
[2024-10-01T10:46:31.454+0000] {subprocess.py:93} INFO - [0m10:46:31  1 of 1 START sql view model analysis.green_trip ................................ [RUN]
[2024-10-01T10:46:31.540+0000] {subprocess.py:93} INFO - [0m10:46:31  1 of 1 ERROR creating sql view model analysis.green_trip ....................... [[31mERROR[0m in 0.08s]
[2024-10-01T10:46:31.551+0000] {subprocess.py:93} INFO - [0m10:46:31
[2024-10-01T10:46:31.552+0000] {subprocess.py:93} INFO - [0m10:46:31  Finished running 1 view model in 0 hours 0 minutes and 0.25 seconds (0.25s).
[2024-10-01T10:46:31.601+0000] {subprocess.py:93} INFO - [0m10:46:31
[2024-10-01T10:46:31.602+0000] {subprocess.py:93} INFO - [0m10:46:31  [31mCompleted with 1 error and 0 warnings:[0m
[2024-10-01T10:46:31.602+0000] {subprocess.py:93} INFO - [0m10:46:31
[2024-10-01T10:46:31.603+0000] {subprocess.py:93} INFO - [0m10:46:31    Database Error in model green_trip (models/Staging/green_trip.sql)
[2024-10-01T10:46:31.604+0000] {subprocess.py:93} INFO -   syntax error at or near ""trip_type""
[2024-10-01T10:46:31.604+0000] {subprocess.py:93} INFO -   LINE 107:         "trip_type" AS trip_type,
[2024-10-01T10:46:31.604+0000] {subprocess.py:93} INFO -                     ^
[2024-10-01T10:46:31.604+0000] {subprocess.py:93} INFO -   compiled code at target/run/fact_trip/models/Staging/green_trip.sql
[2024-10-01T10:46:31.605+0000] {subprocess.py:93} INFO - [0m10:46:31
[2024-10-01T10:46:31.605+0000] {subprocess.py:93} INFO - [0m10:46:31  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-10-01T10:46:32.578+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-01T10:46:32.579+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-01T10:46:32.591+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-01T10:46:32.595+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Taxi_trip_pipeline, task_id=dbt_staging_layer.dbt_run_green_trip, run_id=manual__2024-10-01T10:32:20.925791+00:00, execution_date=20241001T103220, start_date=20241001T104627, end_date=20241001T104632
[2024-10-01T10:46:32.609+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 180 for task dbt_staging_layer.dbt_run_green_trip (Bash command failed. The command returned a non-zero exit code 1.; 771)
[2024-10-01T10:46:32.625+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-01T10:46:32.652+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-01T10:46:32.656+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
